### ISSUE TITLE
[1.7.10] Crash with OpenComputers, Smart Card Terminal

### ISSUE THREAD

**Issue by jrddunbr** [marcin212/Zetta-Industries#75] opened 2018-05-01 03:36 UTC
I'm using the older 1.7.10 version, but this still *may* be a bug worth looking into. I was just fiddling around for fun with some random stuff.

I was right-clicking the OC server rack at the time to open the menu (may have aimed at the terminal itself instead?), which had only one `Smart Card Terminal [WIP]` in it. No servers or anything else in it.

[The whole log](https://paste.ee/p/SxfOJ)

Relevant Portion:
```
java.lang.AbstractMethodError: com.bymarcin.zettaindustries.mods.nfc.smartcard.SmartCardTerminal.onActivate(Lnet/minecraft/entity/player/EntityPlayer;FF)Z
	at li.cil.oc.common.block.Rack.onBlockActivated(Rack.scala:133) ~[Rack.class:?]
	at li.cil.oc.common.block.SimpleBlock.func_149727_a(SimpleBlock.scala:265) ~[SimpleBlock.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
This is about where it happens:

https://github.com/marcin212/Zetta-Industries/blob/9329d1f55232dadd499df8944f834f39e10146cb/src/main/java/com/bymarcin/zettaindustries/mods/nfc/smartcard/SmartCardTerminal.java#L226

Looking a bit closer at the history of the file's changes, it appears that it may have been fixed, but may want to look into it anyways.

**Comment by marcin212** [comment] 2018-05-16 21:04
WIP means Work in Progress. It may crash and not work properly. The 1.7.10 branch is no longer supported. The issue is fixed in 1.12.2.

**Closed as completed by marcin212** 2018-05-16 21:04 UTC
